#!/bin/bash
set -euo pipefail

# Generate Test Data and Reference Position for MADOCA-PPP (madocalib)
#
# This script performs three phases:
#
#   Phase 1 — Prepare test data archive (requires convbin)
#     Cuts the full-day MIZU OBS to 1 hour using convbin, copies NAV/L6E/L6D/ATX
#     from upstream/madocalib/sample_data, and creates the tar.gz archive.
#     Skipped if the archive already exists.
#
#   Phase 2 — Build madocalib binaries
#     Builds rnx2rtkp and cssr2ssr from upstream/madocalib/app/consapp/ source.
#     These are the ORIGINAL madocalib binaries used to generate golden reference.
#
#   Phase 3 — Generate golden reference using madocalib binaries
#     Runs madocalib's rnx2rtkp and cssr2ssr for all test scenarios:
#       1. PPP          (sample.conf,          mdc-004 L6E)
#       2. PPP-AR       (sample_pppar.conf,    mdc-004 L6E)
#       3. PPP-AR 003   (sample_pppar.conf,    mdc-003 L6E)
#       4. PPP-AR+iono  (sample_pppar_iono.conf, mdc-004 L6E+L6D)
#       5. cssr2ssr     (CSSR→SSR conversion)
#
# IMPORTANT: Reference data is generated by MADOCALIB's own binaries, NOT
#            MRTKLIB's. This ensures the golden data represents the correct
#            output of the original implementation.
#
# Data: MIZU station, 2025/04/01 Session A (00:00:00–00:59:30 GPST)
#
# Prerequisites:
#   1. C compiler (gcc or clang)
#   2. convbin binary at project root (or on PATH) — for Phase 1 only
#   3. upstream/madocalib/ populated
#
# Usage:
#   bash tests/data/madocalib/generate_reference_madocalib.sh
#   bash tests/data/madocalib/generate_reference_madocalib.sh --trace     # trace level 5
#   bash tests/data/madocalib/generate_reference_madocalib.sh --trace 3   # custom level
#   bash tests/data/madocalib/generate_reference_madocalib.sh --prepare   # Phase 1 only

# Parse options
TRACE_OPTS=()
PREPARE_ONLY=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --trace)
            level="${2:-5}"
            TRACE_OPTS=(-x "$level")
            echo "Trace enabled (level $level)"
            shift; [[ $# -gt 0 && "$1" =~ ^[0-9]+$ ]] && shift
            ;;
        --prepare)
            PREPARE_ONLY=1
            shift
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Resolve project root from script location
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$ROOT_DIR"

# Directories
DATADIR=tests/data/madocalib
UPSTREAM=upstream/madocalib
UPSTREAM_DATA="${UPSTREAM}/sample_data/data"
UPSTREAM_APP="${UPSTREAM}/app/consapp"
ARCHIVE="${DATADIR}/madocalib_testdata.tar.gz"

# Platform-specific LDLIBS: macOS has no librt
if [[ "$(uname)" == "Darwin" ]]; then
    LDLIBS="-lm"
else
    LDLIBS="-lm -lrt"
fi

# Source files (upstream)
SRC_OBS="${UPSTREAM_DATA}/rinex/MIZU00JPN_R_20250910000_01D_30S_MO.rnx"
SRC_NAV="${UPSTREAM_DATA}/rinex/BRDM00DLR_S_20250910000_01D_MN.rnx"
SRC_L6E1="${UPSTREAM_DATA}/l6_is-qzss-mdc-004/2025/091/2025091A.204.l6"
SRC_L6E2="${UPSTREAM_DATA}/l6_is-qzss-mdc-004/2025/091/2025091A.206.l6"
SRC_L6E1_003="${UPSTREAM_DATA}/l6_is-qzss-mdc-003/2025/091/2025091A.204.l6"
SRC_L6E2_003="${UPSTREAM_DATA}/l6_is-qzss-mdc-003/2025/091/2025091A.206.l6"
SRC_L6D1="${UPSTREAM_DATA}/l6_is-qzss-mdc-004/2025/091/2025091A.200.l6"
SRC_L6D2="${UPSTREAM_DATA}/l6_is-qzss-mdc-004/2025/091/2025091A.201.l6"
SRC_ATX="${UPSTREAM_DATA}/igs20.atx"

# Target files (in test data directory)
OBS="${DATADIR}/MIZU00JPN_R_20250910000_01D_30S_MO.obs"
NAV="${DATADIR}/BRDM00DLR_S_20250910000_01D_MN.rnx"
L6E1="${DATADIR}/2025091A.204.l6"
L6E2="${DATADIR}/2025091A.206.l6"
L6E1_003="${DATADIR}/2025091A.204.mdc003.l6"
L6E2_003="${DATADIR}/2025091A.206.mdc003.l6"
L6D1="${DATADIR}/2025091A.200.l6"
L6D2="${DATADIR}/2025091A.201.l6"
ATX="${DATADIR}/igs20.atx"

# Common rnx2rtkp time options
TS_TE=(-ts 2025/04/01 0:00:00 -te 2025/04/01 0:59:30 -ti 30)

# ── Phase 1: Prepare test data archive ────────────────────────────────────────

if [[ -f "$ARCHIVE" ]]; then
    echo "Archive already exists: $ARCHIVE (skipping Phase 1)"
else
    echo "=== Phase 1: Preparing test data archive ==="

    # Locate convbin
    CONVBIN="${ROOT_DIR}/convbin"
    if [[ ! -x "$CONVBIN" ]]; then
        CONVBIN="$(command -v convbin 2>/dev/null || true)"
    fi
    if [[ -z "$CONVBIN" || ! -x "$CONVBIN" ]]; then
        echo "ERROR: convbin not found." >&2
        echo "  Place the convbin binary at the project root or ensure it is on PATH." >&2
        echo "  (Future: convbin will be built as part of MRTKLIB)" >&2
        exit 1
    fi
    echo "Using convbin: $CONVBIN"

    # Verify upstream source files
    for f in "$SRC_OBS" "$SRC_NAV" \
             "$SRC_L6E1" "$SRC_L6E2" \
             "$SRC_L6E1_003" "$SRC_L6E2_003" \
             "$SRC_L6D1" "$SRC_L6D2" \
             "$SRC_ATX"; do
        if [[ ! -f "$f" ]]; then
            echo "ERROR: Upstream file not found: $f" >&2
            echo "  Ensure upstream/madocalib is populated." >&2
            exit 1
        fi
    done

    # Cut OBS to Session A (00:00:00–00:59:30) using convbin
    echo "Cutting OBS to Session A (00:00:00–00:59:30)..."
    "$CONVBIN" -r rinex -v 3.05 \
        -ts 2025/04/01 0:00:00 -te 2025/04/01 0:59:30 \
        -o "$OBS" "$SRC_OBS"

    if [[ ! -s "$OBS" ]]; then
        echo "ERROR: convbin produced empty output" >&2
        exit 1
    fi
    obs_epochs=$(grep -c "^>" "$OBS" || true)
    echo "  OBS cut: $obs_epochs epochs, $(du -sh "$OBS" | cut -f1)"

    # Copy remaining files
    echo "Copying NAV, L6E (mdc-004), L6E (mdc-003), L6D, ATX..."
    cp "$SRC_NAV"      "$NAV"
    cp "$SRC_L6E1"     "$L6E1"
    cp "$SRC_L6E2"     "$L6E2"
    cp "$SRC_L6E1_003" "$L6E1_003"
    cp "$SRC_L6E2_003" "$L6E2_003"
    cp "$SRC_L6D1"     "$L6D1"
    cp "$SRC_L6D2"     "$L6D2"
    cp "$SRC_ATX"      "$ATX"

    # Create archive
    echo "Creating archive..."
    tar -czf "$ARCHIVE" -C "$DATADIR" \
        "$(basename "$OBS")" \
        "$(basename "$NAV")" \
        "$(basename "$L6E1")" \
        "$(basename "$L6E2")" \
        "$(basename "$L6E1_003")" \
        "$(basename "$L6E2_003")" \
        "$(basename "$L6D1")" \
        "$(basename "$L6D2")" \
        "$(basename "$ATX")"

    archive_size=$(du -sh "$ARCHIVE" | cut -f1)
    echo "  Archive: $ARCHIVE ($archive_size)"

    # Clean up extracted files
    rm -f "$OBS" "$NAV" "$L6E1" "$L6E2" "$L6E1_003" "$L6E2_003" \
          "$L6D1" "$L6D2" "$ATX"

    echo "=== Phase 1 complete ==="
fi

if [[ "$PREPARE_ONLY" -eq 1 ]]; then
    echo "Done (--prepare mode)."
    exit 0
fi

# ── Phase 2: Build madocalib binaries ─────────────────────────────────────────

echo "=== Phase 2: Building madocalib binaries ==="

MDCL_BUILDDIR="${ROOT_DIR}/build/madocalib_ref"
mkdir -p "$MDCL_BUILDDIR"

MDCL_SRC="${UPSTREAM}/src"
MDCL_OPTS="-DTRACE -DENAGLO -DENAQZS -DENAGAL -DENACMP -DENAIRN -DNFREQ=5 -DNEXOBS=5"
MDCL_CFLAGS="-Wall -O3 -ansi -pedantic -I${MDCL_SRC} ${MDCL_OPTS} -g"

# Build rnx2rtkp
echo "Building madocalib rnx2rtkp..."
MDCL_RNX2RTKP_SRCS=(
    "${UPSTREAM_APP}/rnx2rtkp/rnx2rtkp.c"
    "${MDCL_SRC}/rtkcmn.c"
    "${MDCL_SRC}/rinex.c"
    "${MDCL_SRC}/rtkpos.c"
    "${MDCL_SRC}/postpos.c"
    "${MDCL_SRC}/solution.c"
    "${MDCL_SRC}/lambda.c"
    "${MDCL_SRC}/geoid.c"
    "${MDCL_SRC}/sbas.c"
    "${MDCL_SRC}/preceph.c"
    "${MDCL_SRC}/pntpos.c"
    "${MDCL_SRC}/ephemeris.c"
    "${MDCL_SRC}/options.c"
    "${MDCL_SRC}/ppp.c"
    "${MDCL_SRC}/ppp_ar.c"
    "${MDCL_SRC}/ppp_iono.c"
    "${MDCL_SRC}/rtcm.c"
    "${MDCL_SRC}/rtcm2.c"
    "${MDCL_SRC}/rtcm3.c"
    "${MDCL_SRC}/rtcm3e.c"
    "${MDCL_SRC}/ionex.c"
    "${MDCL_SRC}/tides.c"
    "${MDCL_SRC}/mdccssr.c"
    "${MDCL_SRC}/mdciono.c"
)
# shellcheck disable=SC2086
cc $MDCL_CFLAGS -o "${MDCL_BUILDDIR}/rnx2rtkp" "${MDCL_RNX2RTKP_SRCS[@]}" $LDLIBS
echo "  Built: ${MDCL_BUILDDIR}/rnx2rtkp"

# Build cssr2ssr
echo "Building madocalib cssr2ssr..."
MDCL_CSSR2SSR_SRCS=(
    "${UPSTREAM_APP}/cssr2ssr/cssr2ssr.c"
    "${UPSTREAM_APP}/cssr2ssr/cssr.c"
    "${MDCL_SRC}/rtkcmn.c"
    "${MDCL_SRC}/rtcm.c"
    "${MDCL_SRC}/rtcm2.c"
    "${MDCL_SRC}/rtcm3.c"
    "${MDCL_SRC}/rtcm3e.c"
)
# shellcheck disable=SC2086
cc $MDCL_CFLAGS -I"${UPSTREAM_APP}/cssr2ssr" \
    -o "${MDCL_BUILDDIR}/cssr2ssr" "${MDCL_CSSR2SSR_SRCS[@]}" $LDLIBS
echo "  Built: ${MDCL_BUILDDIR}/cssr2ssr"

MDCL_RNX2RTKP="${MDCL_BUILDDIR}/rnx2rtkp"
MDCL_CSSR2SSR="${MDCL_BUILDDIR}/cssr2ssr"

echo "=== Phase 2 complete ==="

# ── Phase 3: Generate golden reference using madocalib binaries ───────────────

echo "=== Phase 3: Generating golden reference (using madocalib binaries) ==="

# Extract test data
echo "Extracting data..."
tar -xzf "$ARCHIVE" -C "$DATADIR"

# Verify inputs exist
for f in "$OBS" "$NAV" "$L6E1" "$L6E2" "$L6E1_003" "$L6E2_003" \
         "$L6D1" "$L6D2"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Input file not found: $f" >&2
        exit 1
    fi
done

# madocalib's conf files (from upstream, with antenna path adjusted)
# We create temporary conf copies with correct antenna file path
MDCL_CONFDIR="${MDCL_BUILDDIR}/conf"
mkdir -p "$MDCL_CONFDIR"

# Use MRTKLIB's conf files (they are faithful copies of madocalib's
# sample configs with only file-rcvantfile path adjusted)
CONF_PPP="conf/madocalib/rnx2rtkp.conf"
CONF_PPPAR="conf/madocalib/rnx2rtkp_pppar.conf"
CONF_PPPAR_IONO="conf/madocalib/rnx2rtkp_pppar_iono.conf"

# Helper to run madocalib's rnx2rtkp and verify
run_madocalib_rnx2rtkp() {
    local label="$1" conf="$2" output="$3"
    shift 3
    echo "Running madocalib rnx2rtkp for ${label}..."
    "$MDCL_RNX2RTKP" \
        -k "$conf" \
        "${TS_TE[@]}" \
        ${TRACE_OPTS[@]+"${TRACE_OPTS[@]}"} \
        -ant "$ATX" \
        -o "$output" \
        "$@"

    if [[ ! -s "$output" ]]; then
        echo "ERROR: Output file not generated or empty: $output" >&2
        exit 1
    fi
    local lines
    lines=$(wc -l < "$output")
    echo "  $output ($lines lines)"
}

# 1. PPP (sample.conf — armode=off, freq=l1+2, iono=dual-freq)
run_madocalib_rnx2rtkp "MADOCA-PPP" \
    "$CONF_PPP" \
    "${DATADIR}/madocalib_MIZU_20250401-0000.pp.pos" \
    "$OBS" "$NAV" "$L6E1" "$L6E2"

# 2. PPP-AR mdc-004 (sample_pppar.conf — armode=continuous, freq=l1+2+3+4)
run_madocalib_rnx2rtkp "MADOCA PPP-AR (mdc-004)" \
    "$CONF_PPPAR" \
    "${DATADIR}/madocalib_MIZU_20250401-0000.pppar.pos" \
    "$OBS" "$NAV" "$L6E1" "$L6E2"

# 3. PPP-AR mdc-003 (same config, different L6E data)
run_madocalib_rnx2rtkp "MADOCA PPP-AR (mdc-003)" \
    "$CONF_PPPAR" \
    "${DATADIR}/madocalib_MIZU_20250401-0000.pppar_003.pos" \
    "$OBS" "$NAV" "$L6E1_003" "$L6E2_003"

# 4. PPP-AR + ionosphere correction (L6E + L6D)
run_madocalib_rnx2rtkp "MADOCA PPP-AR+iono" \
    "$CONF_PPPAR_IONO" \
    "${DATADIR}/madocalib_MIZU_20250401-0000.pppar_ion.pos" \
    "$OBS" "$NAV" "$L6E1" "$L6E2" "$L6D1" "$L6D2"

# 5. cssr2ssr (CSSR→SSR conversion)
echo "Running madocalib cssr2ssr..."
"$MDCL_CSSR2SSR" \
    "$L6E1" \
    -o "${DATADIR}/madocalib_2025091A.204.rtcm3" \
    -td 2025/04/01 -d \
    > "${DATADIR}/madocalib_2025091A.204.l6.txt"
echo "  ${DATADIR}/madocalib_2025091A.204.rtcm3"
echo "  ${DATADIR}/madocalib_2025091A.204.l6.txt"

# Clean up extracted files
rm -f "$OBS" "$NAV" "$L6E1" "$L6E2" "$L6E1_003" "$L6E2_003" \
      "$L6D1" "$L6D2" "$ATX"

echo "=== Phase 3 complete ==="
echo "Reference data generated successfully."
echo ""
echo "Generated reference files:"
for f in "${DATADIR}"/madocalib_*.pos "${DATADIR}"/madocalib_*.rtcm3 \
         "${DATADIR}"/madocalib_*.txt; do
    [[ -f "$f" ]] && echo "  $f ($(wc -l < "$f") lines)"
done
