#!/bin/bash
set -euo pipefail

# Generate Reference Receiver Code Biases using recvbias
#
# This script builds recvbias from upstream/MALIB source and uses it to
# generate golden reference data.
#
# IMPORTANT: Reference data is generated by MALIB's own binaries, NOT
#            MRTKLIB's. This ensures the golden data represents the correct
#            output of the original implementation.
#
# Steps:
#   1. Builds recvbias from upstream/MALIB
#   2. Extracts test data from tests/data/malib/MALIB_OSS_data.tar.gz
#   3. Downloads IONEX TEC data from CODE (Univ. of Bern) if not already present
#   4. Runs recvbias to generate reference receiver code biases
#
# Usage:
#   bash tests/data/malib/generate_reference_recvbias.sh            # without trace
#   bash tests/data/malib/generate_reference_recvbias.sh --trace     # with trace (level 5)
#   bash tests/data/malib/generate_reference_recvbias.sh --trace 3   # with trace (custom level)
#
# Prerequisites:
#   1. C compiler (gcc or clang)
#   2. upstream/MALIB/ populated (git clone)

# Parse options
TRACE_OPTS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --trace)
            if [[ "${2:-}" =~ ^[0-9]+$ ]]; then
                level="$2"
                shift 2
            else
                level=5
                shift
            fi
            TRACE_OPTS=(-t "$level")
            echo "Trace enabled (level $level)"
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Resolve project root from script location
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$ROOT_DIR"

# ── Phase 1: Build MALIB recvbias from upstream source ───────────────────────

echo "=== Phase 1: Building MALIB recvbias ==="

UPSTREAM=upstream/MALIB
if [[ ! -d "$UPSTREAM/src" ]]; then
    echo "ERROR: $UPSTREAM/src not found." >&2
    echo "  Clone MALIB into upstream/MALIB/ first." >&2
    exit 1
fi

MALIB_SRC="${UPSTREAM}/src"
MALIB_APP="${UPSTREAM}/app/consapp"
BUILDDIR="${ROOT_DIR}/build/malib_ref"
mkdir -p "$BUILDDIR"

# Platform-specific: macOS has no librt
if [[ "$(uname)" == "Darwin" ]]; then
    LDLIBS="-lm"
else
    LDLIBS="-lm -lrt"
fi

MALIB_OPTS="-DTRACE -DENAGLO -DENAQZS -DENAGAL -DENACMP -DENAIRN -DNFREQ=5 -DNEXOBS=5 -DPROGNAME=\"recvbias\""
# recvbias uses -std=c99 (overrides -ansi)
MALIB_CFLAGS="-Wall -O3 -ansi -pedantic -I${MALIB_SRC} ${MALIB_OPTS} -g -std=c99"

MALIB_RECVBIAS_SRCS=(
    "${MALIB_APP}/recvbias/recvbias.c"
    "${MALIB_SRC}/biassnx.c"
    "${MALIB_SRC}/ephemeris.c"
    "${MALIB_SRC}/ionex.c"
    "${MALIB_SRC}/lclcmn.c"
    "${MALIB_SRC}/mdccssr.c"
    "${MALIB_SRC}/preceph.c"
    "${MALIB_SRC}/rinex.c"
    "${MALIB_SRC}/rtcm.c"
    "${MALIB_SRC}/rtcm2.c"
    "${MALIB_SRC}/rtcm3.c"
    "${MALIB_SRC}/rtcm3lcl.c"
    "${MALIB_SRC}/rtcm3e.c"
    "${MALIB_SRC}/rtkcmn.c"
    "${MALIB_SRC}/sbas.c"
)

# shellcheck disable=SC2086
cc $MALIB_CFLAGS -o "${BUILDDIR}/recvbias" "${MALIB_RECVBIAS_SRCS[@]}" $LDLIBS
echo "  Built: ${BUILDDIR}/recvbias"

RECVBIAS="${BUILDDIR}/recvbias"
echo "=== Phase 1 complete ==="

# ── Phase 2: Generate reference data using MALIB binary ──────────────────────

echo "=== Phase 2: Generating reference data ==="

# Test parameters
#   Date: 2024-08-22 (DOY 235, GPS week 2328)
#   ECEF position computed from PPP reference output:
#     lat=36.068735658, lon=140.128353589, h=113.288m (WGS84)
DATE="2024/8/22"
ECEF_POS="-3961440.433,3308948.812,3734425.963"
EL_MASK=30

# IONEX TEC file (CODE analysis center, University of Bern)
#   Product: CODE final global ionosphere map (long-name convention)
#   Format:  IONEX 1.0
#   .INX = IONEX TEC grid data (not .ION which is spherical harmonic coefficients)
TEC_BASENAME="COD0OPSFIN_20242350000_01D_01H_GIM.INX"
TEC_FILE="tests/data/malib/${TEC_BASENAME}"
TEC_URL="http://ftp.aiub.unibe.ch/CODE/2024/${TEC_BASENAME}.gz"

# Temporary files to clean up (populated as script runs)
CLEANUP_FILES=()

cleanup() {
    echo "Cleaning up..."
    for f in ${CLEANUP_FILES[@]+"${CLEANUP_FILES[@]}"}; do
        rm -f "$f"
    done
    # Files extracted by tar and downloaded TEC file (be specific to avoid deleting generated files)
    rm -f tests/data/malib/2024235L.209.l6
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.obs
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.nav
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.sbf
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.sbf.tag
    rm -f tests/data/malib/MALIB_OSS_data_l6e_240822-1100.*
    rm -f tests/data/malib/igs14*.atx
    rm -f "tests/data/malib/${TEC_BASENAME}"
}
trap cleanup EXIT

# Extract test data
echo "Extracting data..."
tar -xzf tests/data/malib/MALIB_OSS_data.tar.gz --strip-components=2 -C tests/data/malib

# Download IONEX TEC file if not present in extracted data
if [[ ! -f "$TEC_FILE" ]]; then
    echo "Downloading IONEX TEC file from CODE..."
    echo "  URL: $TEC_URL"
    tec_compressed="${TEC_FILE}.gz"
    if curl -fSL -o "$tec_compressed" "$TEC_URL"; then
        # Use gzip -dc to avoid "has other links" error on APFS (macOS)
        gzip -dc "$tec_compressed" > "$TEC_FILE"
        rm -f "$tec_compressed"
        echo "  Downloaded: $TEC_FILE"
    else
        rm -f "$tec_compressed"
        echo "ERROR: Failed to download IONEX TEC file" >&2
        echo "  URL: $TEC_URL" >&2
        echo "  Please manually download and place at: $TEC_FILE" >&2
        exit 1
    fi
else
    echo "IONEX TEC file already present: $TEC_FILE"
fi

# Input files
obs=tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.obs
nav=tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.nav
l6e=tests/data/malib/2024235L.209.l6

# Output directory
output_dir=tests/data/malib
mkdir -p "$output_dir"

# Execute MALIB recvbias
# Note: recvbias returns exit code 1 on success (non-standard C convention).
#       Exit code 255 (-1 wrapped) indicates actual failure.
output="${output_dir}/MALIB_OSS_data_obsnav_240822-1100.rb.bia"
echo "Running MALIB recvbias..."
set +e
"$RECVBIAS" \
    -td "$DATE" \
    -nav "$nav" \
    -tec "$TEC_FILE" \
    -scb "$l6e" \
    -pos "$ECEF_POS" \
    -el "$EL_MASK" \
    ${TRACE_OPTS[@]+"${TRACE_OPTS[@]}"} \
    -out "$output" \
    "$obs"
rc=$?
set -e

if [[ $rc -ne 0 && $rc -ne 1 ]]; then
    echo "ERROR: recvbias failed (exit code $rc)" >&2
    exit 1
fi

# Verify output
echo "Verifying output..."
if [[ ! -s "$output" ]]; then
    echo "ERROR: Output file not generated or empty: $output" >&2
    exit 1
fi
lines=$(wc -l < "$output")
echo "  $output ($lines lines)"

echo "=== Phase 2 complete ==="
echo "Reference data generated successfully."
