#!/bin/bash
set -euo pipefail

# Generate Reference Position for PPP and SPP using rnx2rtkp
#
# This script builds rnx2rtkp from upstream/MALIB source and uses it to
# generate golden reference data.
#
# IMPORTANT: Reference data is generated by MALIB's own binaries, NOT
#            MRTKLIB's. This ensures the golden data represents the correct
#            output of the original implementation.
#
# Usage:
#   bash tests/data/malib/generate_reference_rnx2rtkp.sh            # without trace
#   bash tests/data/malib/generate_reference_rnx2rtkp.sh --trace     # with trace (level 5)
#   bash tests/data/malib/generate_reference_rnx2rtkp.sh --trace 3   # with trace (custom level)
#
# Prerequisites:
#   1. C compiler (gcc or clang)
#   2. upstream/MALIB/ populated (git clone)

# Parse options
TRACE_OPTS=()
if [[ "${1:-}" == "--trace" ]]; then
    level="${2:-5}"
    TRACE_OPTS=(-x "$level")
    echo "Trace enabled (level $level)"
fi

# Resolve project root from script location
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$ROOT_DIR"

# ── Phase 1: Build MALIB rnx2rtkp from upstream source ───────────────────────

echo "=== Phase 1: Building MALIB rnx2rtkp ==="

UPSTREAM=upstream/MALIB
if [[ ! -d "$UPSTREAM/src" ]]; then
    echo "ERROR: $UPSTREAM/src not found." >&2
    echo "  Clone MALIB into upstream/MALIB/ first." >&2
    exit 1
fi

MALIB_SRC="${UPSTREAM}/src"
MALIB_APP="${UPSTREAM}/app/consapp"
BUILDDIR="${ROOT_DIR}/build/malib_ref"
mkdir -p "$BUILDDIR"

# Platform-specific: macOS has no librt
if [[ "$(uname)" == "Darwin" ]]; then
    LDLIBS="-lm"
else
    LDLIBS="-lm -lrt"
fi

MALIB_OPTS="-DTRACE -DENAGLO -DENAGAL -DENAQZS -DENACMP -DENAIRN -DNFREQ=5 -DNEXOBS=5 -DPROGNAME=\"rnx2rtkp\""
MALIB_CFLAGS="-Wall -O3 -ansi -pedantic -I${MALIB_SRC} ${MALIB_OPTS} -g"

MALIB_RNX2RTKP_SRCS=(
    "${MALIB_APP}/rnx2rtkp/rnx2rtkp.c"
    "${MALIB_SRC}/postpos.c"
    "${MALIB_SRC}/biassnx.c"
    "${MALIB_SRC}/ephemeris.c"
    "${MALIB_SRC}/geoid.c"
    "${MALIB_SRC}/ionex.c"
    "${MALIB_SRC}/lambda.c"
    "${MALIB_SRC}/lclcmn.c"
    "${MALIB_SRC}/mdccssr.c"
    "${MALIB_SRC}/options.c"
    "${MALIB_SRC}/pntpos.c"
    "${MALIB_SRC}/ppp.c"
    "${MALIB_SRC}/ppp_ar.c"
    "${MALIB_SRC}/preceph.c"
    "${MALIB_SRC}/readfcb.c"
    "${MALIB_SRC}/rinex.c"
    "${MALIB_SRC}/rtcm.c"
    "${MALIB_SRC}/rtcm2.c"
    "${MALIB_SRC}/rtcm3.c"
    "${MALIB_SRC}/rtcm3lcl.c"
    "${MALIB_SRC}/rtcm3e.c"
    "${MALIB_SRC}/rtkcmn.c"
    "${MALIB_SRC}/rtkpos.c"
    "${MALIB_SRC}/sbas.c"
    "${MALIB_SRC}/solution.c"
    "${MALIB_SRC}/tides.c"
)

# shellcheck disable=SC2086
cc $MALIB_CFLAGS -o "${BUILDDIR}/rnx2rtkp" "${MALIB_RNX2RTKP_SRCS[@]}" $LDLIBS
echo "  Built: ${BUILDDIR}/rnx2rtkp"

RNX2RTKP="${BUILDDIR}/rnx2rtkp"
echo "=== Phase 1 complete ==="

# ── Phase 2: Generate reference data using MALIB binary ──────────────────────

echo "=== Phase 2: Generating reference data ==="

# Temporary files to clean up (populated as script runs)
CLEANUP_FILES=()

cleanup() {
    echo "Cleaning up..."
    for f in ${CLEANUP_FILES[@]+"${CLEANUP_FILES[@]}"}; do
        rm -f "$f"
    done
    # Files extracted by tar (be specific to avoid deleting generated .pos files)
    rm -f tests/data/malib/2024235L.209.l6
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.obs
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.nav
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.sbf
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.sbf.tag
    rm -f tests/data/malib/MALIB_OSS_data_l6e_240822-1100.*
    rm -f tests/data/malib/igs14*.atx
}
trap cleanup EXIT

# Extract test data
echo "Extracting data..."
tar -xzf tests/data/malib/MALIB_OSS_data.tar.gz --strip-components=2 -C tests/data/malib

# Copy config file
cp conf/malib/rnx2rtkp.conf .
CLEANUP_FILES+=(./rnx2rtkp.conf)

# Input files
obs=tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.obs
nav=tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.nav
l6e=tests/data/malib/2024235L.209.l6

# Output directory
output_dir=tests/data/malib
mkdir -p "$output_dir"

# Execute MALIB rnx2rtkp (PPP)
output="${output_dir}/MALIB_OSS_data_obsnav_240822-1100.pp.pos"
echo "Running MALIB rnx2rtkp for PPP..."
"$RNX2RTKP" -k rnx2rtkp.conf ${TRACE_OPTS[@]+"${TRACE_OPTS[@]}"} -o "$output" "$obs" "$nav" "$l6e"

# Execute MALIB rnx2rtkp (SPP)
output_spp="${output_dir}/MALIB_OSS_data_obsnav_240822-1100.pp.spp.pos"
echo "Running MALIB rnx2rtkp for SPP..."
"$RNX2RTKP" -p 0 -sys G,R,E,J ${TRACE_OPTS[@]+"${TRACE_OPTS[@]}"} -o "$output_spp" "$obs" "$nav"

# Verify outputs
echo "Verifying outputs..."
for f in "$output" "$output_spp"; do
    if [[ ! -s "$f" ]]; then
        echo "ERROR: Output file not generated or empty: $f" >&2
        exit 1
    fi
    lines=$(wc -l < "$f")
    echo "  $f ($lines lines)"
done

echo "=== Phase 2 complete ==="
echo "Reference data generated successfully."
