#!/bin/bash
set -euo pipefail

# Generate Reference Position for real-time PPP using rtkrcv
#
# This script builds rtkrcv from upstream/MALIB source and uses it to
# generate golden reference data.
#
# IMPORTANT: Reference data is generated by MALIB's own binaries, NOT
#            MRTKLIB's. This ensures the golden data represents the correct
#            output of the original implementation.
#
# Usage:
#   bash tests/data/malib/generate_reference_rtkrcv.sh                # default (x10 speed)
#   bash tests/data/malib/generate_reference_rtkrcv.sh --speed 20     # custom playback speed
#   bash tests/data/malib/generate_reference_rtkrcv.sh --trace         # with trace (level 5)
#   bash tests/data/malib/generate_reference_rtkrcv.sh --trace 3       # with trace (custom level)
#
# Prerequisites:
#   1. C compiler (gcc or clang)
#   2. upstream/MALIB/ populated (git clone)
#   3. Linux OS (macOS not supported — MALIB stream.c uses Linux-specific
#      serial/file I/O that causes Bus errors on macOS)

# Defaults
PLAYBACK_SPEED=10
TRACE_LEVEL=0
IDLE_TIMEOUT=10       # seconds of no output growth to consider done
MAX_TIMEOUT=600       # absolute timeout (seconds)
RTKRCV_PORT=52001     # telnet port (avoids /dev/tty requirement)

# Parse options
while [[ $# -gt 0 ]]; do
    case "$1" in
        --speed)
            PLAYBACK_SPEED="${2:?--speed requires a value}"
            shift 2
            ;;
        --trace)
            if [[ "${2:-}" =~ ^[0-9]+$ ]]; then
                TRACE_LEVEL="$2"
                shift 2
            else
                TRACE_LEVEL=5
                shift
            fi
            echo "Trace enabled (level $TRACE_LEVEL)"
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Resolve project root from script location
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$ROOT_DIR"

# ── Phase 1: Build MALIB rtkrcv from upstream source ─────────────────────────

echo "=== Phase 1: Building MALIB rtkrcv ==="

UPSTREAM=upstream/MALIB
if [[ ! -d "$UPSTREAM/src" ]]; then
    echo "ERROR: $UPSTREAM/src not found." >&2
    echo "  Clone MALIB into upstream/MALIB/ first." >&2
    exit 1
fi

MALIB_SRC="${UPSTREAM}/src"
MALIB_APP="${UPSTREAM}/app/consapp"
MALIB_RTKRCV_DIR="${MALIB_APP}/rtkrcv"
BUILDDIR="${ROOT_DIR}/build/malib_ref"
mkdir -p "$BUILDDIR"

# Platform-specific: macOS has no librt, and lacks B460800/B921600 baud constants
if [[ "$(uname)" == "Darwin" ]]; then
    LDLIBS="-lm -lpthread"
    PLATFORM_DEFS="-DB460800=460800 -DB921600=921600"
else
    LDLIBS="-lm -lrt -lpthread"
    PLATFORM_DEFS=""
fi

MALIB_OPTS="-DTRACE -DENAGLO -DENAGAL -DENAQZS -DENACMP -DENAIRN -DNFREQ=5 -DNEXOBS=5 -DPROGNAME=\"rtkrcv\" -DSVR_REUSEADDR"
MALIB_CFLAGS="-Wall -O3 -ansi -pedantic -I${MALIB_SRC} -I${MALIB_RTKRCV_DIR} ${MALIB_OPTS} ${PLATFORM_DEFS} -g"

MALIB_RTKRCV_SRCS=(
    "${MALIB_RTKRCV_DIR}/rtkrcv.c"
    "${MALIB_RTKRCV_DIR}/vt.c"
    "${MALIB_SRC}/rtksvr.c"
    "${MALIB_SRC}/biassnx.c"
    "${MALIB_SRC}/ephemeris.c"
    "${MALIB_SRC}/geoid.c"
    "${MALIB_SRC}/ionex.c"
    "${MALIB_SRC}/lambda.c"
    "${MALIB_SRC}/lclcmn.c"
    "${MALIB_SRC}/mdccssr.c"
    "${MALIB_SRC}/options.c"
    "${MALIB_SRC}/pntpos.c"
    "${MALIB_SRC}/ppp.c"
    "${MALIB_SRC}/ppp_ar.c"
    "${MALIB_SRC}/preceph.c"
    "${MALIB_SRC}/rcvraw.c"
    "${MALIB_SRC}/readfcb.c"
    "${MALIB_SRC}/rinex.c"
    "${MALIB_SRC}/rtcm.c"
    "${MALIB_SRC}/rtcm2.c"
    "${MALIB_SRC}/rtcm3.c"
    "${MALIB_SRC}/rtcm3lcl.c"
    "${MALIB_SRC}/rtcm3e.c"
    "${MALIB_SRC}/rtkcmn.c"
    "${MALIB_SRC}/rtkpos.c"
    "${MALIB_SRC}/sbas.c"
    "${MALIB_SRC}/solution.c"
    "${MALIB_SRC}/stream.c"
    "${MALIB_SRC}/tides.c"
    "${MALIB_SRC}/rcv/binex.c"
    "${MALIB_SRC}/rcv/crescent.c"
    "${MALIB_SRC}/rcv/javad.c"
    "${MALIB_SRC}/rcv/novatel.c"
    "${MALIB_SRC}/rcv/nvs.c"
    "${MALIB_SRC}/rcv/rt17.c"
    "${MALIB_SRC}/rcv/septentrio.c"
    "${MALIB_SRC}/rcv/skytraq.c"
    "${MALIB_SRC}/rcv/ss2.c"
    "${MALIB_SRC}/rcv/ublox.c"
)

# shellcheck disable=SC2086
cc $MALIB_CFLAGS -o "${BUILDDIR}/rtkrcv" "${MALIB_RTKRCV_SRCS[@]}" $LDLIBS
echo "  Built: ${BUILDDIR}/rtkrcv"

RTKRCV="${BUILDDIR}/rtkrcv"
echo "=== Phase 1 complete ==="

# ── Phase 2: Generate reference data using MALIB binary ──────────────────────

echo "=== Phase 2: Generating reference data ==="

# Output paths
output_dir=tests/data/malib
output="${output_dir}/MALIB_OSS_data_obsnav_240822-1100.rt.pos"
mkdir -p "$output_dir"

# PIDs to clean up
RTKRCV_PID=""

cleanup() {
    echo "Cleaning up..."
    # Stop rtkrcv if still running
    if [[ -n "$RTKRCV_PID" ]] && kill -0 "$RTKRCV_PID" 2>/dev/null; then
        echo "  Sending SIGTERM to rtkrcv (PID $RTKRCV_PID)..."
        kill -TERM "$RTKRCV_PID" 2>/dev/null || true
        wait "$RTKRCV_PID" 2>/dev/null || true
    fi
    rm -f ./rtkrcv.toml ./rtkrcv.nav
    # Files extracted by tar (be specific to avoid deleting generated .pos files)
    rm -f tests/data/malib/2024235L.209.l6
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.obs
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.nav
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.sbf
    rm -f tests/data/malib/MALIB_OSS_data_obsnav_240822-1100.sbf.tag
    rm -f tests/data/malib/MALIB_OSS_data_l6e_240822-1100.*
    rm -f tests/data/malib/igs14*.atx
}
trap cleanup EXIT

# Extract test data
echo "Extracting data..."
tar -xzf tests/data/malib/MALIB_OSS_data.tar.gz --strip-components=2 -C tests/data/malib

# Prepare config: copy and patch output path + playback speed
cp conf/malib/rtkrcv.toml ./rtkrcv.toml
python3 -c "
import sys, re
text = open(sys.argv[1]).read()
# Replace output stream1 path
text = re.sub(
    r'(\[streams\.output\.stream1\][^\[]*?path\s*=\s*)\"[^\"]*\"',
    r'\1\"./${output}\"',
    text, count=1, flags=re.DOTALL)
# Replace playback speed
text = re.sub(r'::x[0-9]+', '::x${PLAYBACK_SPEED}', text)
open(sys.argv[1], 'w').write(text)
" ./rtkrcv.toml

echo "Config: playback speed x${PLAYBACK_SPEED}, output -> ${output}"

# Build rtkrcv command
RTKRCV_CMD=("$RTKRCV" -s -p "$RTKRCV_PORT" -o rtkrcv.toml)
if [[ "$TRACE_LEVEL" -gt 0 ]]; then
    RTKRCV_CMD+=(-t "$TRACE_LEVEL")
fi

# Run MALIB rtkrcv in background
echo "Starting MALIB rtkrcv (port $RTKRCV_PORT)..."
"${RTKRCV_CMD[@]}" &
RTKRCV_PID=$!
echo "  rtkrcv PID: $RTKRCV_PID"

# Wait for output file to appear
echo "Waiting for output file..."
elapsed=0
while [[ ! -f "$output" ]]; do
    sleep 1
    elapsed=$((elapsed + 1))
    if [[ $elapsed -ge 30 ]]; then
        echo "ERROR: Output file not created after 30s" >&2
        exit 1
    fi
    if ! kill -0 "$RTKRCV_PID" 2>/dev/null; then
        echo "ERROR: rtkrcv exited unexpectedly" >&2
        exit 1
    fi
done

# Monitor output file: wait until it stops growing
echo "Monitoring output (idle timeout: ${IDLE_TIMEOUT}s, max: ${MAX_TIMEOUT}s)..."
prev_size=0
idle_count=0
total_elapsed=0

while true; do
    sleep 1
    total_elapsed=$((total_elapsed + 1))

    # Check rtkrcv is still alive
    if ! kill -0 "$RTKRCV_PID" 2>/dev/null; then
        echo "  rtkrcv exited on its own."
        break
    fi

    # Check absolute timeout
    if [[ $total_elapsed -ge $MAX_TIMEOUT ]]; then
        echo "WARNING: Max timeout (${MAX_TIMEOUT}s) reached. Stopping." >&2
        break
    fi

    # Check output file size
    if [[ -f "$output" ]]; then
        curr_size=$(wc -c < "$output")
    else
        curr_size=0
    fi

    if [[ "$curr_size" -eq "$prev_size" ]]; then
        idle_count=$((idle_count + 1))
        if [[ $idle_count -ge $IDLE_TIMEOUT ]]; then
            echo "  Output stable for ${IDLE_TIMEOUT}s. Processing complete."
            break
        fi
    else
        idle_count=0
        prev_size=$curr_size
    fi

    # Progress indicator every 30s
    if [[ $((total_elapsed % 30)) -eq 0 ]]; then
        lines=$(wc -l < "$output" 2>/dev/null || echo 0)
        echo "  [${total_elapsed}s] ${lines} lines written..."
    fi
done

# Graceful shutdown
echo "Stopping rtkrcv..."
if kill -0 "$RTKRCV_PID" 2>/dev/null; then
    kill -TERM "$RTKRCV_PID"
    wait "$RTKRCV_PID" 2>/dev/null || true
fi
RTKRCV_PID=""  # prevent double-kill in cleanup

# Verify output
echo "Verifying output..."
if [[ ! -s "$output" ]]; then
    echo "ERROR: Output file not generated or empty: $output" >&2
    exit 1
fi
lines=$(wc -l < "$output")
echo "  $output ($lines lines)"

echo "=== Phase 2 complete ==="
echo "Reference data generated successfully."
